name: test ci/cd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: geo_locations_in_russia
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
      - name: install Depend
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress
      - name: wailt for mysql
        run: |
          for i in $(seq 1 10); do
            nc -z mysql 3306 && break || sleep 5
          done
      - name: conf db env
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=geo_locations_in_russia" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
      - name: copy env file
        run: cp .env.example .env 
      - name: genertae key
        run: echo "APP_KEY=base64:VvLjuukNwqzPw6mWnW4LBKpanXwgasote+f1qp9Gf2Y=" >> .env
      - name: conf env
        run: |
          php artisan migrate --env=testing
      - name: start testing
        run: php artisan test --env=testing --verbose
