name: test ci/cd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
      - name: install Depend
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress
      - name: wailt for mysql
        run: |
          for i in $(seq 1 10); do
            nc -z mysql 3306 && break || sleep 5
          done
      - name: copy env file
        run: cp .env.example .env
      - name: conf db env
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=test_db" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
      - name: conf env
        run: |
          php artisan key:generate
          php artisan migrate --env=testing
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl
      - name: install Depend
        run: composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress
      - name: test
        run: php artisan test --env=testing
